"use strict";
/**
 * Regression test for lr-f7c100: on a Codex session driven by a human
 * through the console, the console must declare human presence to LORE
 * (`lore session attest-human <codex-thread-id>`) the moment the Codex
 * thread/rollout id first becomes known — this is the earliest point the
 * console can call the declarer, well before any turn completes and
 * LORE's sentinel evaluates a dispatch decision for that session id.
 *
 * Three properties, each a hard boundary per the task:
 *   1. A human-driven Codex session's first-known session id IS attested.
 *   2. A headless Codex session (session.humanOriginated unset — the
 *      structural signal set only by project-user-message.js's WS
 *      "message"/"send_scheduled_now" handlers) is NEVER attested.
 *   3. A human-driven CLAUDE session is NOT attested here — Claude console
 *      sessions are already covered by LORE's own pulse hook (see
 *      lib/lore-attestation.js header); duplicating the call for Claude
 *      is out of scope and untested here by design (vendor gate).
 *
 * Drives the real attachMessageProcessor()/processSDKMessage() code path,
 * same harness pattern as sdk-message-processor-auto-title-gate-lr-62157d.test.js.
 * lib/lore-attestation.js itself is stubbed (module-level function swap) so
 * this test never shells out to a real `lore` binary.
 */

var test = require("node:test");
var assert = require("node:assert/strict");

var loreAttestation = require("../lib/lore-attestation");
var { attachMessageProcessor } = require("../lib/sdk-message-processor");

function makeSm() {
  return {
    skillMeta: [],
    workflowMeta: [],
    skillNames: [],
    slashCommands: null,
    currentModel: null,
    _savedDefaultModel: null,
    permissionRequestIndex: {},
    sendAndRecord: function (session, obj) {
      if (!session.history) session.history = [];
      session.history.push(obj);
    },
    sendToSession: function () {},
    saveSessionFile: function () {},
    broadcastSessionList: function () {},
    modelsByVendor: {},
    availableModels: [],
    availableVendors: [],
    installedVendors: [],
  };
}

function makeProcessor(sm, vendor) {
  return attachMessageProcessor({
    sm: sm,
    send: function () {},
    slug: "test-slug",
    cwd: "/tmp",
    pushModule: null,
    getNotificationsModule: function () { return null; },
    adapter: { vendor: vendor || "codex" },
    onProcessingChanged: function () {},
    onTurnDone: null,
    onAutoTitle: null,
    opts: {},
    discoverSkillDirs: function () { return []; },
    mergeSkills: function () { return []; },
    discoverWorkflows: function () { return []; },
    discoverSkillsWithMeta: function () { return []; },
    mergeSkillsWithMeta: function () { return []; },
    getSDK: null,
  });
}

function makeSession(overrides) {
  var base = {
    localId: 1,
    cliSessionId: null,
    vendor: "codex",
    history: [],
    messageUUIDs: [],
    blocks: {},
    sentToolResults: {},
    pendingPermissions: {},
    pendingElicitations: {},
    pendingAskUser: {},
    activeTaskToolIds: {},
    taskIdMap: {},
    streamedText: false,
    responsePreview: "",
    isProcessing: true,
    loop: null,
    titleAutoGenerated: false,
    titleManuallySet: false,
  };
  return Object.assign(base, overrides || {});
}

// Fires the synthetic event that carries the vendor's session id for the
// first time — this is exactly what happens when Codex's thread/start (or
// Claude SDK's init) result reaches processSDKMessage with a fresh sessionId.
function fireFirstSessionId(processor, session, sessionId) {
  processor.processSDKMessage(session, {
    yokeType: "init",
    sessionId: sessionId,
  });
}

test("lr-f7c100: a human-driven Codex session is attested on first-known session id", function (t) {
  var calls = [];
  var original = loreAttestation.attestHumanSession;
  loreAttestation.attestHumanSession = function (sid) { calls.push(sid); };
  t.after(function () { loreAttestation.attestHumanSession = original; });

  var sm = makeSm();
  var processor = makeProcessor(sm, "codex");
  var session = makeSession({ localId: 201, vendor: "codex", humanOriginated: true });

  fireFirstSessionId(processor, session, "codex-thread-abc123");

  assert.deepEqual(calls, ["codex-thread-abc123"], "attest-human must be called exactly once, keyed on the Codex thread id");
});

test("lr-f7c100: a headless Codex session (no human turn) is NEVER attested", function (t) {
  var calls = [];
  var original = loreAttestation.attestHumanSession;
  loreAttestation.attestHumanSession = function (sid) { calls.push(sid); };
  t.after(function () { loreAttestation.attestHumanSession = original; });

  var sm = makeSm();
  var processor = makeProcessor(sm, "codex");
  // Ralph Loop / external-trigger / scheduler sessions never set
  // humanOriginated — this is the default-deny case the hard boundary
  // protects: over-attesting a headless spawn defeats the gate.
  var session = makeSession({ localId: 202, vendor: "codex", loop: { loopId: "loop-1" } });

  fireFirstSessionId(processor, session, "codex-thread-headless-xyz");

  assert.deepEqual(calls, [], "a session with no human turn must never be attested, regardless of vendor");
});

test("lr-f7c100: a human-driven CLAUDE session is not attested by this code path (pulse hook already covers it)", function (t) {
  var calls = [];
  var original = loreAttestation.attestHumanSession;
  loreAttestation.attestHumanSession = function (sid) { calls.push(sid); };
  t.after(function () { loreAttestation.attestHumanSession = original; });

  var sm = makeSm();
  var processor = makeProcessor(sm, "claude");
  var session = makeSession({ localId: 203, vendor: "claude", humanOriginated: true });

  fireFirstSessionId(processor, session, "claude-cli-session-def456");

  assert.deepEqual(calls, [], "Claude sessions are covered by LORE's own pulse hook — the console must not duplicate the call");
});

test("lr-f7c100: attestation fires only once per session, not on every subsequent turn", function (t) {
  var calls = [];
  var original = loreAttestation.attestHumanSession;
  loreAttestation.attestHumanSession = function (sid) { calls.push(sid); };
  t.after(function () { loreAttestation.attestHumanSession = original; });

  var sm = makeSm();
  var processor = makeProcessor(sm, "codex");
  var session = makeSession({ localId: 204, vendor: "codex", humanOriginated: true });

  fireFirstSessionId(processor, session, "codex-thread-once");
  // A later event carrying the SAME session id must not re-fire — the
  // "_isNewSessionId" gate in sdk-message-processor.js is the same one used
  // for the existing session_id wire message, and this call rides that gate.
  processor.processSDKMessage(session, { yokeType: "text_delta", sessionId: "codex-thread-once" });

  assert.deepEqual(calls, ["codex-thread-once"], "attest-human must not be re-invoked once the session id is already known");
});
