"use strict";
/**
 * Regression test for lr-62157d (MILLER fnd-d21956, keystone cause #3):
 * the first-message provisional title (project-user-message.js) looked
 * exactly like a real title — nothing distinguished "already properly
 * titled" from "still carrying the raw 50-char truncation" — so
 * autoGenerateTitle's guard in sdk-bridge.js never had a signal telling it
 * it was safe to overwrite. Every session kept its provisional truncation
 * forever, even once autoGenerateTitle actually ran.
 *
 * Fix: session.titleProvisional marks a title set by the first-message
 * fallback; autoGenerateTitle now overwrites when
 * (titleProvisional || !title) && !titleManuallySet.
 *
 * Drives the real autoGenerateTitle() closure from lib/sdk-bridge.js
 * (exposed as _test_autoGenerateTitle for this purpose — see codex.js's
 * _test_resolveTitleModel for the established precedent) — no
 * reimplementation of the guard logic.
 */

var test = require("node:test");
var assert = require("node:assert/strict");

function freshSdkBridge() {
  var modPath = require.resolve("../lib/sdk-bridge");
  delete require.cache[modPath];
  return require("../lib/sdk-bridge");
}

function makeSm(overrides) {
  var sm = {
    defaultVendor: "claude",
    saveSessionFile: function () {},
    broadcastSessionList: function () {},
    loadFullSessionHistory: function () {},
    retrimHistory: function () {},
  };
  return Object.assign(sm, overrides || {});
}

function makeAdapter(generatedTitle) {
  return {
    vendor: "claude",
    generateTitle: function () { return Promise.resolve(generatedTitle); },
    renameSession: function () { return Promise.resolve(); },
  };
}

function makeSession(overrides) {
  var base = {
    localId: 1,
    cliSessionId: null,
    vendor: "claude",
    history: [
      { type: "user_message", text: "hello there, this is my first message" },
    ],
    _historyBaseIndex: 0,
    title: "",
    titleProvisional: false,
    titleAutoGenerated: false,
    titleManuallySet: false,
  };
  return Object.assign(base, overrides || {});
}

function makeBridge(sm, adapter) {
  var { createSDKBridge } = freshSdkBridge();
  return createSDKBridge({
    cwd: "/tmp/test-project-lr62157d",
    sessionManager: sm,
    send: function () {},
    adapter: adapter,
    adapters: { claude: adapter },
    onProcessingChanged: function () {},
  });
}

test("lr-62157d: autoGenerateTitle REPLACES a provisional title (titleProvisional=true) with the LLM-generated title", function () {
  var sm = makeSm();
  var adapter = makeAdapter("A Real Generated Title");
  var bridge = makeBridge(sm, adapter);
  var session = makeSession({
    title: "hello there, this is my first mess", // raw 50-char truncation, the pre-fix signature
    titleProvisional: true,
  });

  return bridge._test_autoGenerateTitle(session).then(function () {
    assert.equal(session.title, "A Real Generated Title", "provisional title must be replaced by the real generated title");
    assert.equal(session.titleAutoGenerated, true);
    assert.equal(session.titleProvisional, false, "titleProvisional must be cleared once a real title lands");
  });
});

test("lr-62157d: autoGenerateTitle does NOT replace a user-set title (titleManuallySet=true), even if titleProvisional is also true", function () {
  var sm = makeSm();
  var adapter = makeAdapter("A Real Generated Title");
  var bridge = makeBridge(sm, adapter);
  var session = makeSession({
    title: "My Custom Renamed Title",
    titleManuallySet: true,
    titleProvisional: false,
  });

  return bridge._test_autoGenerateTitle(session).then(function () {
    assert.equal(session.title, "My Custom Renamed Title", "a manually-renamed title must never be overwritten by auto-title");
    assert.equal(session.titleAutoGenerated, false);
  });
});

test("lr-62157d: autoGenerateTitle fills in a title when none exists yet (no title, titleProvisional false) as long as not manually set", function () {
  var sm = makeSm();
  var adapter = makeAdapter("Freshly Generated Title");
  var bridge = makeBridge(sm, adapter);
  var session = makeSession({
    title: "",
    titleProvisional: false,
    titleManuallySet: false,
  });

  return bridge._test_autoGenerateTitle(session).then(function () {
    assert.equal(session.title, "Freshly Generated Title");
    assert.equal(session.titleAutoGenerated, true);
  });
});

test("lr-62157d: a second autoGenerateTitle call does NOT clobber an already-real (non-provisional) title", function () {
  var sm = makeSm();
  var adapter = makeAdapter("Second Call Title");
  var bridge = makeBridge(sm, adapter);
  var session = makeSession({
    title: "First Generated Title",
    titleAutoGenerated: true,
    titleProvisional: false,
    titleManuallySet: false,
  });

  // autoGenerateTitle's own guard is (titleProvisional || !title) &&
  // !titleManuallySet -- it does NOT re-check titleAutoGenerated itself
  // (that re-fire prevention lives in sdk-message-processor.js's trigger
  // gate). What DOES stop a second call from clobbering a real title here
  // is that the title is present and no longer provisional -- this test
  // pins that half of the guard directly, independent of the trigger gate.
  return bridge._test_autoGenerateTitle(session).then(function () {
    assert.equal(session.title, "First Generated Title", "a real, non-provisional title must not be overwritten by a later autoGenerateTitle call");
  });
});
