"use strict";
/**
 * Regression test for lr-62157d (MILLER fnd-d21956): the auto-title trigger
 * in sdk-message-processor.js's 'result' handler used exact equality
 * (`session.turnCount === AUTO_TITLE_TURN_THRESHOLD`), so any turn that
 * incremented past the threshold turn without evaluating the gate (early
 * return, error path, non-result terminal event, or — before this task's
 * durability fix — a turnCount that reset to 0 on a daemon restart)
 * permanently disqualified the session from ever being auto-titled again.
 *
 * Fix: '===' -> '>=', so a missed window self-heals on a later turn instead
 * of disqualifying the session forever. Idempotence still comes from
 * !session.titleAutoGenerated.
 *
 * Drives the real attachMessageProcessor()/processSDKMessage() code path
 * from lib/sdk-message-processor.js with a synthetic 'result' event — same
 * pattern as test/permission-request-index-sweep-lr-f940.test.js.
 */

var test = require("node:test");
var assert = require("node:assert/strict");

var { attachMessageProcessor } = require("../lib/sdk-message-processor");

function makeSm() {
  return {
    skillMeta: [],
    workflowMeta: [],
    skillNames: [],
    slashCommands: null,
    currentModel: null,
    _savedDefaultModel: null,
    permissionRequestIndex: {},
    sendAndRecord: function (session, obj) {
      if (!session.history) session.history = [];
      session.history.push(obj);
    },
    sendToSession: function () {},
    saveSessionFile: function () {},
    broadcastSessionList: function () {},
    modelsByVendor: {},
    availableModels: [],
    availableVendors: [],
    installedVendors: [],
  };
}

function makeProcessor(sm, onAutoTitle) {
  return attachMessageProcessor({
    sm: sm,
    send: function () {},
    slug: "test-slug",
    cwd: "/tmp",
    pushModule: null,
    getNotificationsModule: function () { return null; },
    adapter: { vendor: "claude" },
    onProcessingChanged: function () {},
    onTurnDone: null,
    onAutoTitle: onAutoTitle || null,
    opts: {},
    discoverSkillDirs: function () { return []; },
    mergeSkills: function () { return []; },
    discoverWorkflows: function () { return []; },
    discoverSkillsWithMeta: function () { return []; },
    mergeSkillsWithMeta: function () { return []; },
    getSDK: null,
  });
}

function makeSession(overrides) {
  var base = {
    localId: 1,
    cliSessionId: null,
    vendor: "claude",
    history: [],
    messageUUIDs: [],
    blocks: {},
    sentToolResults: {},
    pendingPermissions: {},
    pendingElicitations: {},
    pendingAskUser: {},
    activeTaskToolIds: {},
    taskIdMap: {},
    streamedText: false,
    responsePreview: "",
    isProcessing: true,
    loop: null,
    titleAutoGenerated: false,
    titleManuallySet: false,
  };
  return Object.assign(base, overrides || {});
}

function fireResult(processor, session, cost) {
  processor.processSDKMessage(session, {
    yokeType: "result",
    cost: cost === undefined ? 0.1 : cost,
    duration: 500,
    sessionId: "cli-session-lr62157d",
  });
}

test("lr-62157d: a session that SKIPS PAST the exact turn-2 window (turnCount jumps 1 -> 3) still fires auto-title on that later turn", function () {
  var sm = makeSm();
  var firedForSessions = [];
  var processor = makeProcessor(sm, function (session) { firedForSessions.push(session.localId); });
  var session = makeSession({ localId: 101, turnCount: 2 }); // one turn already elapsed pre-jump

  // Simulate a turn boundary that jumps the counter past 2 directly to 3 —
  // e.g. a resumed/rehydrated session whose turnCount was not incremented
  // through the normal 1 -> 2 -> 3 path. The 'result' handler itself does
  // session.turnCount = (session.turnCount || 0) + 1, so starting turnCount
  // at 2 here means this fireResult call lands on turnCount === 3.
  fireResult(processor, session);

  assert.equal(session.turnCount, 3, "sanity: turnCount incremented past the exact threshold");
  assert.deepEqual(firedForSessions, [101], "onAutoTitle must still fire when turnCount lands past (not exactly on) the threshold — this is the '>=' fix; it fails against '===' pre-fix code");
});

test("lr-62157d: a session that lands EXACTLY on the turn-2 threshold still fires (no regression on the original case)", function () {
  var sm = makeSm();
  var firedForSessions = [];
  var processor = makeProcessor(sm, function (session) { firedForSessions.push(session.localId); });
  var session = makeSession({ localId: 102, turnCount: 1 });

  fireResult(processor, session);

  assert.equal(session.turnCount, 2);
  assert.deepEqual(firedForSessions, [102], "the original exact-threshold case must keep working");
});

test("lr-62157d: titleAutoGenerated correctly suppresses a second fire on a later turn (idempotence)", function () {
  var sm = makeSm();
  var fireCount = 0;
  var processor = makeProcessor(sm, function () { fireCount++; });
  var session = makeSession({ localId: 103, turnCount: 1 });

  fireResult(processor, session); // turnCount -> 2, fires once
  assert.equal(fireCount, 1);

  // Simulate autoGenerateTitle's own effect (sdk-bridge.js) having landed
  // between turns, as it would in production once the async generateTitle()
  // promise resolves.
  session.titleAutoGenerated = true;

  fireResult(processor, session); // turnCount -> 3, must NOT fire again
  assert.equal(fireCount, 1, "titleAutoGenerated=true must suppress every subsequent turn's gate, not just the immediate next one");

  fireResult(processor, session); // turnCount -> 4, still must not fire
  assert.equal(fireCount, 1);
});

test("lr-62157d: a loop session never fires auto-title regardless of turnCount (pre-existing exclusion, unaffected by the >= change)", function () {
  var sm = makeSm();
  var fireCount = 0;
  var processor = makeProcessor(sm, function () { fireCount++; });
  var session = makeSession({ localId: 104, turnCount: 5, loop: { loopId: "loop-1" } });

  fireResult(processor, session);

  assert.equal(fireCount, 0, "session.loop must still exclude auto-title firing");
});

test("lr-62157d: a session with titleManuallySet=true never fires auto-title even past the threshold", function () {
  var sm = makeSm();
  var fireCount = 0;
  var processor = makeProcessor(sm, function () { fireCount++; });
  var session = makeSession({ localId: 105, turnCount: 4, titleManuallySet: true });

  fireResult(processor, session);

  assert.equal(fireCount, 0, "a manually-renamed session must never be auto-titled");
});
