"use strict";
/**
 * lr-efdab6 (DRUMMER decision, comment #1 on lr-efdab6; Part 2 of the
 * two-part mechanism, Part 1 is a DRUMMER check_set out of this repo):
 *
 * The auto-title gate in sdk-message-processor.js's 'result' handler
 * (~:792, the lr-62157d '>=' gate) logged on every branch it TOOK
 * (sdk-bridge.js's [auto-title] sites) but nothing recorded the branch it
 * did NOT take. Silence at that point in the log read identically for "ran
 * fine and logged nothing notable", "never invoked", and "invoked and died
 * before the first log" -- the exact ambiguity that let auto-title run dead
 * for ~3 months / ~160 sessions with no signal. This test drives the real
 * gate (attachMessageProcessor / processSDKMessage, same harness as
 * test/sdk-message-processor-auto-title-gate-lr-62157d.test.js) and asserts
 * on captured console output for each not-fired reason, so it fails against
 * pre-fix code (no else branch => no [auto-title] "gate did not fire" line
 * at all, for every one of these cases) and passes once the reason is
 * emitted.
 */

var test = require("node:test");
var assert = require("node:assert/strict");

var { attachMessageProcessor } = require("../lib/sdk-message-processor");

function makeSm() {
  return {
    skillMeta: [],
    workflowMeta: [],
    skillNames: [],
    slashCommands: null,
    currentModel: null,
    _savedDefaultModel: null,
    permissionRequestIndex: {},
    sendAndRecord: function (session, obj) {
      if (!session.history) session.history = [];
      session.history.push(obj);
    },
    sendToSession: function () {},
    saveSessionFile: function () {},
    broadcastSessionList: function () {},
    modelsByVendor: {},
    availableModels: [],
    availableVendors: [],
    installedVendors: [],
  };
}

function makeProcessor(sm, onAutoTitle) {
  return attachMessageProcessor({
    sm: sm,
    send: function () {},
    slug: "test-slug",
    cwd: "/tmp",
    pushModule: null,
    getNotificationsModule: function () { return null; },
    adapter: { vendor: "claude" },
    onProcessingChanged: function () {},
    onTurnDone: null,
    onAutoTitle: onAutoTitle === undefined ? function () {} : onAutoTitle,
    opts: {},
    discoverSkillDirs: function () { return []; },
    mergeSkills: function () { return []; },
    discoverWorkflows: function () { return []; },
    discoverSkillsWithMeta: function () { return []; },
    mergeSkillsWithMeta: function () { return []; },
    getSDK: null,
  });
}

function makeSession(overrides) {
  var base = {
    localId: 1,
    cliSessionId: null,
    vendor: "claude",
    history: [],
    messageUUIDs: [],
    blocks: {},
    sentToolResults: {},
    pendingPermissions: {},
    pendingElicitations: {},
    pendingAskUser: {},
    activeTaskToolIds: {},
    taskIdMap: {},
    streamedText: false,
    responsePreview: "",
    isProcessing: true,
    loop: null,
    titleAutoGenerated: false,
    titleManuallySet: false,
  };
  return Object.assign(base, overrides || {});
}

function fireResult(processor, session, cost) {
  processor.processSDKMessage(session, {
    yokeType: "result",
    cost: cost === undefined ? 0.1 : cost,
    duration: 500,
    sessionId: "cli-session-lr-efdab6",
  });
}

// Captures console.log/console.debug calls for the duration of fn(), then
// restores the originals. Returns the array of joined-string lines.
function captureConsole(fn) {
  var lines = [];
  var origLog = console.log;
  var origDebug = console.debug;
  console.log = function () { lines.push(Array.prototype.slice.call(arguments).join(" ")); };
  console.debug = function () { lines.push(Array.prototype.slice.call(arguments).join(" ")); };
  try {
    fn();
  } finally {
    console.log = origLog;
    console.debug = origDebug;
  }
  return lines;
}

function findGateLine(lines) {
  return lines.filter(function (l) { return l.indexOf("[auto-title] gate did not fire:") === 0; });
}

test("lr-efdab6: turn_threshold_not_met reason logged when turnCount has not reached the threshold", function () {
  var sm = makeSm();
  var processor = makeProcessor(sm, function () {});
  var session = makeSession({ localId: 201, turnCount: 0 }); // -> 1 after fireResult, threshold is 2

  var lines = captureConsole(function () { fireResult(processor, session); });
  var gateLines = findGateLine(lines);

  assert.equal(gateLines.length, 1, "exactly one not-fired gate line must be emitted; fails against pre-fix code, which emits none");
  assert.match(gateLines[0], /reason=turn_threshold_not_met/);
  assert.match(gateLines[0], /turnCount=1/);
  assert.match(gateLines[0], /titleAutoGenerated=false/);
  assert.match(gateLines[0], /titleManuallySet=false/);
  assert.match(gateLines[0], /loop=false/);
});

test("lr-efdab6: manually_set reason logged even though turnCount is past threshold", function () {
  var sm = makeSm();
  var processor = makeProcessor(sm, function () {});
  var session = makeSession({ localId: 202, turnCount: 4, titleManuallySet: true });

  var lines = captureConsole(function () { fireResult(processor, session); });
  var gateLines = findGateLine(lines);

  assert.equal(gateLines.length, 1, "fails against pre-fix code (no line emitted at all)");
  assert.match(gateLines[0], /reason=manually_set/);
  assert.match(gateLines[0], /titleManuallySet=true/);
});

test("lr-efdab6: loop_running reason logged for a session mid-loop, regardless of turnCount", function () {
  var sm = makeSm();
  var processor = makeProcessor(sm, function () {});
  var session = makeSession({ localId: 203, turnCount: 5, loop: { loopId: "loop-1" } });

  var lines = captureConsole(function () { fireResult(processor, session); });
  var gateLines = findGateLine(lines);

  assert.equal(gateLines.length, 1, "fails against pre-fix code (no line emitted at all)");
  assert.match(gateLines[0], /reason=loop_running/);
  assert.match(gateLines[0], /loop=true/);
});

test("lr-efdab6: no_callback reason logged when onAutoTitle was never wired up", function () {
  var sm = makeSm();
  var processor = makeProcessor(sm, null); // onAutoTitle explicitly absent
  var session = makeSession({ localId: 204, turnCount: 3 });

  var lines = captureConsole(function () { fireResult(processor, session); });
  var gateLines = findGateLine(lines);

  assert.equal(gateLines.length, 1, "fails against pre-fix code (no line emitted at all)");
  assert.match(gateLines[0], /reason=no_callback/);
});

test("lr-efdab6: already_auto_generated reason logged on the steady-state turn after a title has been generated, at debug level not log level", function () {
  var sm = makeSm();
  var processor = makeProcessor(sm, function () {});
  var session = makeSession({ localId: 205, turnCount: 1, titleAutoGenerated: true });

  var logLines = [];
  var debugLines = [];
  var origLog = console.log;
  var origDebug = console.debug;
  console.log = function () { logLines.push(Array.prototype.slice.call(arguments).join(" ")); };
  console.debug = function () { debugLines.push(Array.prototype.slice.call(arguments).join(" ")); };
  try {
    fireResult(processor, session);
  } finally {
    console.log = origLog;
    console.debug = origDebug;
  }

  var gateLogLines = logLines.filter(function (l) { return l.indexOf("[auto-title] gate did not fire:") === 0; });
  var gateDebugLines = debugLines.filter(function (l) { return l.indexOf("[auto-title] gate did not fire:") === 0; });

  assert.equal(gateLogLines.length, 0, "steady-state already_auto_generated must NOT use console.log (would dominate journald at ~1 line/turn for every mature session)");
  assert.equal(gateDebugLines.length, 1, "already_auto_generated must still be recorded, at console.debug, so the negative branch is never silently dropped -- fails against pre-fix code either way (no line at any level)");
  assert.match(gateDebugLines[0], /reason=already_auto_generated/);
  assert.match(gateDebugLines[0], /titleAutoGenerated=true/);
});

test("lr-efdab6: the fired path (gate takes the if branch) never emits a not-fired line", function () {
  var sm = makeSm();
  var processor = makeProcessor(sm, function () {});
  var session = makeSession({ localId: 206, turnCount: 1 }); // -> 2 after fireResult, meets threshold, nothing else set

  var lines = captureConsole(function () { fireResult(processor, session); });
  var gateLines = findGateLine(lines);

  assert.equal(gateLines.length, 0, "when the gate fires, the not-fired else branch must not also log");
});
