"use strict";
/**
 * Regression test for lr-62157d (MILLER fnd-d21956/fnd-3291e4, keystone
 * cause): titleAutoGenerated, titleManuallySet and turnCount were never
 * written by buildMetaLine() and never hydrated by loadSessions() — every
 * daemon restart silently reset all three to false/0, so the "already
 * auto-titled" / "user renamed it" guards in sdk-message-processor.js and
 * sdk-bridge.js were guarding against state that could never survive a
 * restart. Across ~160 real session files on this machine, zero meta lines
 * ever contained titleAutoGenerated or titleManuallySet — this is the live
 * evidence that motivated the fix.
 *
 * Drives real production code (buildMetaLine via saveSessionFile, and
 * loadSessions via a fresh createSessionManager pointed at the same
 * CLAGENTIC_HOME) — no reimplementation. Modeled on the existing
 * test/session-meta-rewrite-lr-79c6.test.js round-trip pattern.
 */

var test = require("node:test");
var assert = require("node:assert/strict");
var fs = require("fs");
var path = require("path");
var os = require("os");

function makeTempHome() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "clagentic-test-lr62157d-"));
}

function makeSessionManager(tmpHome) {
  ["../lib/config", "../lib/sessions", "../lib/utils"].forEach(function (m) {
    try { delete require.cache[require.resolve(m)]; } catch (_) {}
  });
  var origHome = process.env.CLAGENTIC_HOME;
  process.env.CLAGENTIC_HOME = tmpHome;
  var sessions;
  try {
    sessions = require("../lib/sessions");
  } finally {
    if (origHome === undefined) delete process.env.CLAGENTIC_HOME;
    else process.env.CLAGENTIC_HOME = origHome;
  }
  return sessions.createSessionManager({
    cwd: tmpHome,
    send: function () {},
    sendTo: function () {},
    sendEach: function () {},
  });
}

test("lr-62157d: titleAutoGenerated, titleManuallySet and turnCount survive a daemon restart (buildMetaLine -> loadSessions round trip)", function () {
  var tmpHome = makeTempHome();
  try {
    var sm1 = makeSessionManager(tmpHome);
    var sess = sm1.createSessionRaw({});
    sess.cliSessionId = "sess-62157d-flags";
    sess.title = "A real LLM-generated title";
    sess.titleAutoGenerated = true;
    sess.titleManuallySet = false;
    sess.titleProvisional = false;
    sess.turnCount = 7;
    sm1.saveSessionFile(sess);

    // Simulate a full daemon restart: brand-new SessionManager, same on-disk
    // home, so this exercises loadSessions()'s hydration path exactly as a
    // real restart would.
    var sm2 = makeSessionManager(tmpHome);
    var reloaded = null;
    sm2.sessions.forEach(function (s) {
      if (s.cliSessionId === "sess-62157d-flags") reloaded = s;
    });

    assert.ok(reloaded, "reloaded session must be found after restart");
    assert.equal(reloaded.titleAutoGenerated, true, "titleAutoGenerated must survive a restart");
    assert.equal(reloaded.titleManuallySet, false, "titleManuallySet must survive a restart (as false here)");
    assert.equal(reloaded.turnCount, 7, "turnCount must survive a restart");
  } finally {
    fs.rmSync(tmpHome, { recursive: true, force: true });
  }
});

test("lr-62157d: titleManuallySet=true survives a daemon restart (durable suppression of auto-title)", function () {
  var tmpHome = makeTempHome();
  try {
    var sm1 = makeSessionManager(tmpHome);
    var sess = sm1.createSessionRaw({});
    sess.cliSessionId = "sess-62157d-manual";
    sess.title = "User Renamed This";
    sess.titleManuallySet = true;
    sess.titleAutoGenerated = false;
    sm1.saveSessionFile(sess);

    var sm2 = makeSessionManager(tmpHome);
    var reloaded = null;
    sm2.sessions.forEach(function (s) {
      if (s.cliSessionId === "sess-62157d-manual") reloaded = s;
    });

    assert.ok(reloaded);
    assert.equal(reloaded.titleManuallySet, true, "a user-set title's flag must remain true after restart");
  } finally {
    fs.rmSync(tmpHome, { recursive: true, force: true });
  }
});

test("lr-62157d: titleProvisional survives a daemon restart", function () {
  var tmpHome = makeTempHome();
  try {
    var sm1 = makeSessionManager(tmpHome);
    var sess = sm1.createSessionRaw({});
    sess.cliSessionId = "sess-62157d-provisional";
    sess.title = "raw first message trunc";
    sess.titleProvisional = true;
    sm1.saveSessionFile(sess);

    var sm2 = makeSessionManager(tmpHome);
    var reloaded = null;
    sm2.sessions.forEach(function (s) {
      if (s.cliSessionId === "sess-62157d-provisional") reloaded = s;
    });

    assert.ok(reloaded);
    assert.equal(reloaded.titleProvisional, true, "titleProvisional must survive a restart");
  } finally {
    fs.rmSync(tmpHome, { recursive: true, force: true });
  }
});

test("lr-62157d: a session that never set the flags reloads with false/0, not undefined (no crash on later boolean/arithmetic use)", function () {
  var tmpHome = makeTempHome();
  try {
    var sm1 = makeSessionManager(tmpHome);
    var sess = sm1.createSessionRaw({});
    sess.cliSessionId = "sess-62157d-defaults";
    sess.title = "";
    sm1.saveSessionFile(sess);

    var sm2 = makeSessionManager(tmpHome);
    var reloaded = null;
    sm2.sessions.forEach(function (s) {
      if (s.cliSessionId === "sess-62157d-defaults") reloaded = s;
    });

    assert.ok(reloaded);
    assert.equal(reloaded.titleAutoGenerated, false);
    assert.equal(reloaded.titleManuallySet, false);
    assert.equal(reloaded.titleProvisional, false);
    assert.equal(reloaded.turnCount, 0);
  } finally {
    fs.rmSync(tmpHome, { recursive: true, force: true });
  }
});

test("lr-62157d: buildMetaLine (via saveSessionFile) writes titleAutoGenerated/titleManuallySet/turnCount to the on-disk meta line when true/nonzero", function () {
  var tmpHome = makeTempHome();
  try {
    var sm = makeSessionManager(tmpHome);
    var sess = sm.createSessionRaw({});
    sess.cliSessionId = "sess-62157d-ondisk";
    sess.title = "Some Title";
    sess.titleAutoGenerated = true;
    sess.turnCount = 3;
    sm.saveSessionFile(sess);

    var sessionsBase = path.join(tmpHome, "console", "sessions");
    var sessionFile = null;
    fs.readdirSync(sessionsBase).forEach(function (dir) {
      var candidate = path.join(sessionsBase, dir, "sess-62157d-ondisk.jsonl");
      if (fs.existsSync(candidate)) sessionFile = candidate;
    });
    assert.ok(sessionFile, "session file must exist on disk");

    var firstLine = fs.readFileSync(sessionFile, "utf8").split("\n")[0];
    var meta = JSON.parse(firstLine);
    assert.equal(meta.titleAutoGenerated, true, "meta line must carry titleAutoGenerated:true");
    assert.equal(meta.turnCount, 3, "meta line must carry turnCount");
    assert.equal(meta.titleManuallySet, undefined, "false-valued flags stay absent, matching the bookmarked/pendingAutoResume write-when-true convention");
  } finally {
    fs.rmSync(tmpHome, { recursive: true, force: true });
  }
});
