// memory-limits.js — daemon.json advanced-settings override for systemd memory limits
// and MemoryHigh watermark detection (lr-de07).
//
// DESIGN: The shipped unit file (deploy/clagentic-console.service) carries
// percentage-based defaults (MemoryHigh=70%, MemoryMax=85%) that auto-scale when
// RAM is added. This module handles OPTIONAL operator overrides only: when
// config.memoryMax / config.memoryHigh are absent, the shipped defaults win and
// nothing here changes any behavior.
//
// Override reach: a systemd drop-in written to
//   /etc/systemd/system/clagentic-console.service.d/memory-overrides.conf
// overrides only the MemoryMax and MemoryHigh [Service] lines. All other unit
// settings remain exactly as shipped.

'use strict';

var fs = require('fs');
var path = require('path');

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

var DROP_IN_DIR = '/etc/systemd/system/clagentic-console.service.d';
var DROP_IN_FILE = path.join(DROP_IN_DIR, 'memory-overrides.conf');

// Accepted units for absolute memory values.
// Systemd accepts K, M, G, T (case-insensitive) and bare bytes.
var ABS_PATTERN = /^(\d+(?:\.\d+)?)\s*([KMGT]?)B?$/i;
var PCT_PATTERN = /^(\d+(?:\.\d+)?)\s*%$/;

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Parse and validate a memory limit value accepted by systemd MemoryMax/MemoryHigh.
 *
 * Accepts:
 *   - Percentage string: '70%', '85%'  (0 < value <= 100)
 *   - Absolute with suffix: '6G', '512M', '2T', '1024K', '8192'
 *
 * Returns { ok: true, value: <normalized-string> } on success, where the
 * normalized value is the canonical string to write into the drop-in.
 * Returns { ok: false, error: <string> } on failure.
 *
 * @param {string} raw
 * @returns {{ ok: boolean, value?: string, error?: string }}
 */
function parseMemoryLimit(raw) {
  if (typeof raw !== 'string' || !raw.trim()) {
    return { ok: false, error: 'memory limit must be a non-empty string' };
  }
  var s = raw.trim();

  // Percentage
  var pctMatch = s.match(PCT_PATTERN);
  if (pctMatch) {
    var pct = parseFloat(pctMatch[1]);
    if (isNaN(pct) || pct <= 0 || pct > 100) {
      return { ok: false, error: 'percentage must be between 0 (exclusive) and 100 (inclusive), got: ' + raw };
    }
    // Systemd requires integer percentages in unit files; reject fractional.
    if (pct !== Math.floor(pct)) {
      return { ok: false, error: 'percentage must be a whole number, got: ' + raw };
    }
    return { ok: true, value: Math.round(pct) + '%' };
  }

  // Absolute value with optional suffix
  var absMatch = s.match(ABS_PATTERN);
  if (absMatch) {
    var num = parseFloat(absMatch[1]);
    var suffix = (absMatch[2] || '').toUpperCase();
    if (isNaN(num) || num <= 0) {
      return { ok: false, error: 'absolute memory value must be positive, got: ' + raw };
    }
    // Reject fractional bytes (no suffix) — ambiguous.
    if (!suffix && num !== Math.floor(num)) {
      return { ok: false, error: 'bare byte count must be a whole number, got: ' + raw };
    }
    // Normalize: integer + suffix, e.g. '6G', '512M'
    var normalized = (Number.isInteger(num) ? num : num) + suffix;
    return { ok: true, value: normalized };
  }

  return { ok: false, error: 'unrecognized memory limit format (expected NNN%, NG, NM, NK, or bare bytes): ' + raw };
}

// ---------------------------------------------------------------------------
// Drop-in rendering
// ---------------------------------------------------------------------------

/**
 * Render the content of the systemd drop-in file for memory overrides.
 *
 * Only MemoryHigh and/or MemoryMax are emitted — one or both depending on
 * which overrides are present. If neither is set, returns null (no drop-in
 * should be written).
 *
 * The drop-in first resets each directive to empty (clears the shipped default)
 * then sets the operator-supplied value, per systemd drop-in semantics.
 *
 * @param {{ memoryHigh?: string, memoryMax?: string }} opts
 * @returns {string|null}
 */
function renderDropIn(opts) {
  var lines = ['# Generated by Clagentic: Console (lr-de07). Do not edit manually.',
               '# Remove this file and run systemctl daemon-reload to restore shipped defaults.',
               '[Service]'];
  var hasAny = false;

  if (opts.memoryHigh) {
    var hRes = parseMemoryLimit(opts.memoryHigh);
    if (!hRes.ok) throw new Error('memoryHigh: ' + hRes.error);
    // Reset then set (systemd drop-in semantics: empty value clears inherited).
    lines.push('MemoryHigh=');
    lines.push('MemoryHigh=' + hRes.value);
    hasAny = true;
  }

  if (opts.memoryMax) {
    var mRes = parseMemoryLimit(opts.memoryMax);
    if (!mRes.ok) throw new Error('memoryMax: ' + mRes.error);
    lines.push('MemoryMax=');
    lines.push('MemoryMax=' + mRes.value);
    hasAny = true;
  }

  if (!hasAny) return null;
  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Drop-in apply (called from postinstall.js after root check)
// ---------------------------------------------------------------------------

/**
 * Write (or remove) the memory-overrides drop-in based on daemon.json config.
 *
 * When neither config.memoryHigh nor config.memoryMax is set, any existing
 * drop-in is removed so shipped defaults take effect after daemon-reload.
 *
 * Validates values before writing — throws on invalid input so postinstall
 * can log and abort rather than silently writing a broken unit.
 *
 * @param {{ memoryHigh?: string, memoryMax?: string }} cfg  — subset of daemon.json
 * @param {function(string): void} [log]  — optional logger (defaults to console.log)
 */
function applyDropIn(cfg, log) {
  var _log = log || function (msg) { console.log(msg); };

  var hasOverride = cfg && (cfg.memoryHigh || cfg.memoryMax);
  if (!hasOverride) {
    // Remove drop-in if present so shipped defaults take over.
    try {
      if (fs.existsSync(DROP_IN_FILE)) {
        fs.unlinkSync(DROP_IN_FILE);
        _log('[memory-limits] Removed ' + DROP_IN_FILE + ' (no overrides configured — shipped defaults apply)');
      }
    } catch (e) {
      _log('[memory-limits] WARNING: could not remove drop-in ' + DROP_IN_FILE + ': ' + e.message);
    }
    return;
  }

  // Render — throws on invalid format.
  var content = renderDropIn({ memoryHigh: cfg.memoryHigh, memoryMax: cfg.memoryMax });
  if (!content) return; // shouldn't happen given hasOverride check

  try {
    fs.mkdirSync(DROP_IN_DIR, { recursive: true });
  } catch (e) {
    throw new Error('Cannot create drop-in dir ' + DROP_IN_DIR + ': ' + e.message);
  }

  // Atomic write via tmp-rename.
  var tmp = DROP_IN_FILE + '.tmp';
  try {
    fs.writeFileSync(tmp, content, { mode: 0o644 });
    fs.renameSync(tmp, DROP_IN_FILE);
    _log('[memory-limits] Wrote memory-overrides drop-in to ' + DROP_IN_FILE);
    if (cfg.memoryHigh) _log('[memory-limits]   MemoryHigh=' + cfg.memoryHigh);
    if (cfg.memoryMax)  _log('[memory-limits]   MemoryMax=' + cfg.memoryMax);
  } catch (e) {
    try { fs.unlinkSync(tmp); } catch (_) {}
    throw new Error('Cannot write drop-in ' + DROP_IN_FILE + ': ' + e.message);
  }
}

// ---------------------------------------------------------------------------
// MemoryHigh watermark watcher
// ---------------------------------------------------------------------------

// How often to poll for the MemoryHigh watermark (ms).
// Long enough to avoid hot-loop cost; short enough to catch a crossing quickly.
var POLL_INTERVAL_MS = 5000;

/**
 * Derive the MemoryHigh threshold in bytes from config and the live cgroup.
 *
 * Priority:
 *   1. config.memoryHigh (operator override, parsed to bytes)
 *   2. The live cgroup v2 memory.high value (covers both shipped % default and drop-in)
 *   3. null (no threshold determinable)
 *
 * @param {{ memoryHigh?: string }} cfg
 * @returns {number|null}  threshold in bytes, or null
 */
function resolveMemoryHighBytes(cfg) {
  // 1. Operator override in config.
  if (cfg && cfg.memoryHigh) {
    var parsed = parseMemoryLimit(cfg.memoryHigh);
    if (parsed.ok) {
      var b = memoryValueToBytes(parsed.value);
      if (b !== null) return b;
    }
  }

  // 2. Live cgroup v2 value (covers percentage defaults and already-applied drop-ins).
  try {
    var cgDir = '/sys/fs/cgroup/system.slice/clagentic-console.service';
    var highRaw = fs.readFileSync(cgDir + '/memory.high', 'utf8').trim();
    if (highRaw !== 'max' && highRaw !== '') {
      var highBytes = parseInt(highRaw, 10);
      if (!isNaN(highBytes) && highBytes > 0) return highBytes;
    }
  } catch (_) {}

  return null;
}

/**
 * Convert a normalized memory limit string to bytes.
 * Returns null if it cannot be resolved to a byte count at runtime
 * (e.g. a percentage string — percentage resolution requires total RAM).
 *
 * @param {string} value  — e.g. '6G', '512M', '70%'
 * @returns {number|null}
 */
function memoryValueToBytes(value) {
  if (!value) return null;

  // Percentage: resolve against /proc/meminfo MemTotal.
  var pctMatch = value.match(/^(\d+(?:\.\d+)?)%$/);
  if (pctMatch) {
    try {
      var raw = fs.readFileSync('/proc/meminfo', 'utf8');
      var match = raw.match(/^MemTotal:\s+(\d+)\s+kB/m);
      if (!match) return null;
      var totalBytes = parseInt(match[1], 10) * 1024;
      return Math.floor(totalBytes * parseFloat(pctMatch[1]) / 100);
    } catch (_) {
      return null;
    }
  }

  // Absolute with suffix.
  var absMatch = value.match(/^(\d+(?:\.\d+)?)([KMGT]?)$/i);
  if (!absMatch) return null;
  var n = parseFloat(absMatch[1]);
  var unit = (absMatch[2] || '').toUpperCase();
  var multipliers = { '': 1, K: 1024, M: 1024 * 1024, G: 1024 * 1024 * 1024, T: 1024 * 1024 * 1024 * 1024 };
  var mul = multipliers[unit];
  if (mul === undefined) return null;
  return Math.floor(n * mul);
}

/**
 * Read the cgroup v2 memory.events 'high' counter for the service cgroup.
 * Returns the counter value as a number, or null if unavailable.
 *
 * @returns {number|null}
 */
function readCgroupHighCounter() {
  try {
    var cgDir = '/sys/fs/cgroup/system.slice/clagentic-console.service';
    var raw = fs.readFileSync(cgDir + '/memory.events', 'utf8');
    var match = raw.match(/^high\s+(\d+)/m);
    if (match) return parseInt(match[1], 10);
  } catch (_) {}
  return null;
}

/**
 * Read the current cgroup v2 RSS (memory.current) in bytes, or null.
 *
 * @returns {number|null}
 */
function readCgroupCurrentBytes() {
  try {
    var cgDir = '/sys/fs/cgroup/system.slice/clagentic-console.service';
    var raw = fs.readFileSync(cgDir + '/memory.current', 'utf8').trim();
    var n = parseInt(raw, 10);
    return isNaN(n) ? null : n;
  } catch (_) {}
  return null;
}

/**
 * Start polling for MemoryHigh watermark crossings and emit a structured log
 * event when the soft memory ceiling is breached.
 *
 * Detection strategy (in priority order):
 *   A. cgroup v2 memory.events 'high' counter increment — most accurate;
 *      fired by the kernel when the service's memory usage exceeds MemoryHigh.
 *   B. memory.current vs resolved MemoryHigh threshold — fallback when the
 *      cgroup path is not accessible (e.g. running outside systemd in dev).
 *
 * De-duplication: once a watermark-crossing event is emitted, no further events
 * are emitted until the memory drops back below the threshold and rises again
 * (for counter-based detection: until the last-seen counter value changes again
 * after a reset; for RSS-based: until RSS drops below threshold by a 5% hysteresis
 * before re-alerting).
 *
 * The emitted log line is a JSON object on stderr so that structured log
 * consumers (lr-6b30 and friends) can parse it without log-parsing fragility.
 *
 * @param {{ memoryHigh?: string, memoryMax?: string }} cfg  — subset of daemon.json
 * @param {object} [opts]
 * @param {number} [opts.pollIntervalMs]  — polling interval (default 5000)
 * @param {function(object): void} [opts.onCrossing]  — called with the same
 *   detail object that is written to the log whenever a watermark crossing is
 *   detected. Consumers (lr-6b30 drain) use this instead of parsing stderr.
 * @returns {{ stop: function(): void }}  handle to stop the watcher
 */
function startMemoryHighWatcher(cfg, opts) {
  var pollMs = (opts && opts.pollIntervalMs) || POLL_INTERVAL_MS;
  var onCrossing = (opts && typeof opts.onCrossing === 'function') ? opts.onCrossing : null;

  // State for de-duplication.
  var lastHighCounter = null;      // last 'high' counter value seen (strategy A)
  var isAboveThreshold = false;    // for strategy B hysteresis
  var HYSTERESIS_FRACTION = 0.05;  // 5% drop required before re-alerting

  var handle = setInterval(function () {
    try {
      _poll(cfg);
    } catch (e) {
      // Polling must never crash the daemon.
    }
  }, pollMs);

  // Unref so the watcher doesn't keep the process alive if everything else exits.
  if (handle && typeof handle.unref === 'function') handle.unref();

  function _emitWarning(detail) {
    var event = {
      event: 'memory_high_watermark',
      source: detail.source,
      timestamp: new Date().toISOString(),
    };
    if (detail.highCounter !== undefined) event.highCounter = detail.highCounter;
    if (detail.currentBytes !== undefined) event.currentBytes = detail.currentBytes;
    if (detail.thresholdBytes !== undefined) event.thresholdBytes = detail.thresholdBytes;
    // Emit as a prefixed JSON line on stderr (journald captures stderr to the journal).
    process.stderr.write('[memory-limits] WARN memory_high_watermark ' + JSON.stringify(event) + '\n');
    // Notify any registered crossing consumer (e.g. lr-6b30 drain controller).
    if (onCrossing) {
      try { onCrossing(event); } catch (_) {}
    }
  }

  function _poll(c) {
    // Strategy A: cgroup v2 memory.events high counter.
    var highCounter = readCgroupHighCounter();
    if (highCounter !== null) {
      if (lastHighCounter === null) {
        // First observation — record baseline, do not alert.
        lastHighCounter = highCounter;
        return;
      }
      if (highCounter > lastHighCounter) {
        // Counter advanced — kernel confirmed a MemoryHigh crossing.
        var currentBytes = readCgroupCurrentBytes();
        _emitWarning({
          source: 'cgroup.memory.events',
          highCounter: highCounter,
          currentBytes: currentBytes !== null ? currentBytes : undefined,
        });
        lastHighCounter = highCounter;
      }
      // Counter-based path is definitive — skip RSS fallback.
      return;
    }

    // Strategy B: compare RSS against resolved threshold.
    var threshold = resolveMemoryHighBytes(c);
    if (threshold === null) return; // no threshold determinable

    var currentB = readCgroupCurrentBytes();
    if (currentB === null) {
      // Fallback: use process.memoryUsage().rss when cgroup current is unavailable.
      currentB = process.memoryUsage().rss;
    }

    var hysteresisBytes = Math.floor(threshold * HYSTERESIS_FRACTION);
    if (!isAboveThreshold && currentB > threshold) {
      isAboveThreshold = true;
      _emitWarning({
        source: 'rss_vs_threshold',
        currentBytes: currentB,
        thresholdBytes: threshold,
      });
    } else if (isAboveThreshold && currentB < threshold - hysteresisBytes) {
      // Memory dropped back below threshold (with hysteresis) — reset so a
      // future crossing triggers another warning.
      isAboveThreshold = false;
    }
  }

  return {
    stop: function () {
      clearInterval(handle);
    },
  };
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = {
  DROP_IN_DIR: DROP_IN_DIR,
  DROP_IN_FILE: DROP_IN_FILE,
  parseMemoryLimit: parseMemoryLimit,
  renderDropIn: renderDropIn,
  applyDropIn: applyDropIn,
  resolveMemoryHighBytes: resolveMemoryHighBytes,
  memoryValueToBytes: memoryValueToBytes,
  readCgroupHighCounter: readCgroupHighCounter,
  readCgroupCurrentBytes: readCgroupCurrentBytes,
  startMemoryHighWatcher: startMemoryHighWatcher,
  // Exposed for testing only.
  _POLL_INTERVAL_MS: POLL_INTERVAL_MS,
};
